displayName=Plugin Troubleshooter
author=swirle13
description=Quickly find which plugin is causing a problem using binary search bisect
tags=help,fix,problem,issue,trouble,troubleshoot,debug,support,error,broken,diagnose,find,bisect
plugins=com.github.swirle13.plugintroubleshooter.PluginTroubleshooterPlugin
